"""change minmax

Revision ID: 9c38240b2261
Revises: 5e7296eca581
Create Date: 2025-08-24 07:51:10.215994+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c38240b2261'
down_revision: Union[str, None] = '5e7296eca581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               comment='게시글 내용 (선택, 최대 100자)',
               existing_comment='게시글 내용 (선택, 50-100자)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               comment='게시글 내용 (선택, 50-100자)',
               existing_comment='게시글 내용 (선택, 최대 100자)',
               existing_nullable=True)
    # ### end Alembic commands ###
