"""Add pg_tid column to payments table

Revision ID: 6526c518097a
Revises: d4f394bd27db
Create Date: 2025-08-19 23:31:31.498296+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6526c518097a'
down_revision: Union[str, None] = 'd4f394bd27db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('pg_tid', sa.String(length=200), nullable=True, comment='PG 결제 TID (환불용)'))
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.VARCHAR(length=200),
               comment='PG 거래 ID (AID)',
               existing_comment='PG 거래 ID',
               existing_nullable=False)
    op.alter_column('subscriptions', 'cancel_reason',
               existing_type=sa.TEXT(),
               comment='취소 사유',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'cancel_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='취소 사유',
               existing_nullable=True)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.VARCHAR(length=200),
               comment='PG 거래 ID',
               existing_comment='PG 거래 ID (AID)',
               existing_nullable=False)
    op.drop_column('payments', 'pg_tid')
    # ### end Alembic commands ###
