"""update post

Revision ID: 437f25425f39
Revises: 6b08ef06703c
Create Date: 2025-08-23 01:43:15.341861+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '437f25425f39'
down_revision: Union[str, None] = '6b08ef06703c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='게시글 내용 (선택, 50-100자)',
               existing_comment='게시글 내용 (50-100자)')
    op.alter_column('posts', 'image_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               comment='이미지 URL 배열 (필수, 1-4장)',
               existing_comment='이미지 URL 배열')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment='이미지 URL 배열',
               existing_comment='이미지 URL 배열 (필수, 1-4장)')
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='게시글 내용 (50-100자)',
               existing_comment='게시글 내용 (선택, 50-100자)')
    # ### end Alembic commands ###
